-- 設定値
-- 01. タイムゾーン
alter database postgres set timezone to 'Asia/Tokyo';

-- 拡張機能
-- 01. 最終更新時刻
create extension if not exists moddatetime schema extensions;

-- テーブル定義
-- 02.権限
-- -- テーブル
CREATE TABLE permissions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  permission_name TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT '1',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  descriptions TEXT
);

-- -- トリガー
create trigger handle_permissions_updated_at before update on permissions
  for each row execute procedure moddatetime (updated_at);

-- 03.ユーザ権限
-- -- テーブル
CREATE TABLE user_permissions (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id),
  permission_id INT NOT NULL REFERENCES permissions(id),
  status TEXT NOT NULL DEFAULT '1',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -- トリガー
create trigger handle_user_permissions_updated_at before update on user_permissions
  for each row execute procedure moddatetime (updated_at);

-- -- RLS
alter table user_permissions enable row level security;
create policy "Users can view their own user_permissions."
  on public.user_permissions
  for select
  to authenticated
  using (
    auth.uid() = user_permissions.user_id
  );

-- -- RLS * 02.権限
alter table permissions enable row level security;
create policy "Users can view their own permissions."
  on public.permissions
  for select
  to authenticated
  using (
    auth.uid() in (
      select user_id
        from user_permissions
        where user_permissions.permission_id = permissions.id
    )
  );



